// SPDX-FileCopyrightText: 2026 Max Veregge
// SPDX-License-Identifier: AGPL-3.0-or-later

namespace Dbr.Domain.Monitoring;

/// <summary>
/// Which day of the month a given account's scans run on.
/// </summary>
/// <remarks>
/// <para>
/// Monthly monitoring anchored to the same calendar date for everybody would have every
/// broker see the whole service arrive at once on the first, which per-broker pacing then
/// spends the rest of the day draining. The two controls are complementary: this stops a
/// thundering herd forming, the queue lanes absorb whatever forms anyway.
/// </para>
/// <para>
/// <b>The day is derived from the account id and stored nowhere.</b> A column would be a
/// second copy that could disagree with this function, and would need backfilling for
/// every existing account the day it was added. Derived, an account's day is settled the
/// moment it exists and cannot drift.
/// </para>
/// </remarks>
public static class ScanSchedule
{
    /// <summary>
    /// The days a scheduled scan can land on.
    /// </summary>
    /// <remarks>
    /// Twenty-eight rather than thirty-one, because the point is a monthly rhythm and the
    /// last three days of the month do not happen every month. An account hashed onto the
    /// 31st would be scanned seven times a year; one on the 29th would be skipped in most
    /// Februaries. Spreading over the days every month actually has keeps the interval
    /// uniform, which matters more than using the whole calendar.
    /// </remarks>
    public const int SpreadDays = 28;

    /// <summary>
    /// The day of the month <paramref name="tenantId"/>'s scheduled scans run on, from 1
    /// to <see cref="SpreadDays"/>.
    /// </summary>
    public static int DayOfMonthFor(Guid tenantId) => 1 + (int)(Hash(tenantId) % SpreadDays);

    /// <summary>Whether this account's scans are due on <paramref name="date"/>.</summary>
    public static bool IsDue(Guid tenantId, DateOnly date) => DayOfMonthFor(tenantId) == date.Day;

    /// <summary>
    /// FNV-1a over the id's sixteen bytes.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Written out rather than reached for from the framework, and this is the one part of
    /// this file worth being careful about. <see cref="string.GetHashCode()"/> and
    /// <see cref="HashCode"/> are randomized per process: they would give a stable answer
    /// within one run of the worker and a different one after a restart, so an account's
    /// scan day would move every deploy and the monthly rhythm would quietly become
    /// "whenever the process last started". That failure produces no error and no log
    /// line.
    /// </para>
    /// <para>
    /// Over all sixteen bytes rather than the last four. Ids are generated by
    /// <c>gen_random_uuid()</c> and are random throughout, so either would spread evenly
    /// today — but an operator importing accounts with sequential or prefixed ids would
    /// find a suffix-only hash piling them onto a handful of days, which is the exact
    /// thing this exists to prevent.
    /// </para>
    /// </remarks>
    private static uint Hash(Guid tenantId)
    {
        Span<byte> bytes = stackalloc byte[16];
        tenantId.TryWriteBytes(bytes);

        var hash = 2166136261u;

        foreach (var b in bytes)
        {
            hash ^= b;
            hash *= 16777619u;
        }

        return hash;
    }
}
