// SPDX-FileCopyrightText: 2026 Max Veregge
// SPDX-License-Identifier: AGPL-3.0-or-later

using Dbr.Domain.Profiles;
using Dbr.Domain.Tenancy;

namespace Dbr.Domain.Vault;

/// <summary>
/// Permission for one piece of work to see part of one identity, once.
/// </summary>
/// <remarks>
/// <para>
/// <b>A capability, not a lookup.</b> The process that needs an identity holds no keys
/// and no vault connection, deliberately — it drives browsers against sites that have no
/// interest in being read, and a credential that could decrypt would be a standing right
/// sitting in the most exposed part of the system. So it asks a process that does hold
/// them, and what it presents is this: an unguessable secret minted for exactly one leg
/// of work. Presenting it is the authentication; this row only turns it into a name.
/// </para>
/// <para>
/// The alternative was to let the asker name the work — a scan id and a certificate — and
/// that is the shape this deliberately does not have. <b>A scan id is not a secret</b>: it
/// is generated by the service and handed straight back to whoever asked for the scan. A
/// grant resolvable from one would rest entirely on the transport being configured
/// correctly, which is a property of a deployment rather than of the schema. Keyed to a
/// digest, the release is as strong as the token whether or not the edge in front of it
/// is what anybody thinks it is.
/// </para>
/// <para>
/// <b>One leg of work, not one scan.</b> A scan fans out to a broker at a time, each paced
/// separately and each running whenever its lane allows, so one grant covering the whole
/// run would be a key with a long life and many holders. This is per broker, which keeps
/// what a leaked one opens down to a single company's leg.
/// </para>
/// <para>
/// The token itself is not here and never was: what is stored is its digest, so reading
/// this table yields nothing anybody can present.
/// </para>
/// </remarks>
public class IdentityRelease : ITenantScoped
{
    public Guid Id { get; init; }

    /// <summary>The account whose identity this permits reading.</summary>
    public Guid TenantId { get; init; }

    /// <summary>The run this leg belongs to.</summary>
    public required Guid ScanId { get; init; }

    /// <summary>The company this leg is addressed to.</summary>
    public required Guid BrokerId { get; init; }

    /// <summary>Which identity is being released.</summary>
    /// <remarks>
    /// Denormalized from the scan and pinned to it by a foreign key over the pair, so the
    /// grant cannot come to name a different profile than the run it was minted for.
    /// </remarks>
    public required Guid PrivacyProfileId { get; init; }

    /// <summary>
    /// SHA-256 of the token. The token is 256 bits from a CSPRNG, so there is nothing to
    /// guess and no reason to pay for a slow hash on a path a scan hits once per broker.
    /// </summary>
    public required byte[] TokenHash { get; init; }

    /// <summary>
    /// The groups this grant covers, and the ceiling on what redeeming it decrypts.
    /// </summary>
    /// <remarks>
    /// Recorded rather than recomputed at redemption. What a search declares it needs can
    /// change with a deploy; what was actually handed over on a Tuesday cannot, and the
    /// second is the question somebody asks afterwards.
    /// </remarks>
    public required IReadOnlyList<IdentityField> Fields { get; init; }

    public DateTimeOffset IssuedAt { get; init; }

    /// <summary>
    /// When it stops being redeemable, whether or not anybody used it.
    /// </summary>
    /// <remarks>
    /// Short, and short for a reason that is not about theft: a grant minted when a leg
    /// was queued and redeemed when its lane finally allowed it could otherwise sit
    /// unredeemed for as long as the queue is deep. A window that outlives the work is a
    /// window in which a message sitting in a queue is a decryption right.
    /// </remarks>
    public required DateTimeOffset ExpiresAt { get; init; }

    /// <summary>
    /// When it was spent, or <see langword="null"/> while it has not been.
    /// </summary>
    /// <remarks>
    /// A timestamp rather than a flag, because the question asked afterwards is when
    /// somebody's identity was decrypted and by which piece of work — and a boolean
    /// answers neither. This is the record the audit trail will carry when there is one;
    /// until then it is the record.
    /// </remarks>
    public DateTimeOffset? RedeemedAt { get; set; }
}
