// SPDX-FileCopyrightText: 2026 Max Veregge
// SPDX-License-Identifier: AGPL-3.0-or-later

using Dbr.Domain.Profiles;
using Dbr.Domain.Tenancy;

namespace Dbr.Domain.Vault;

/// <summary>
/// Permission for one piece of work to see part of one identity, once.
/// </summary>
/// <remarks>
/// <para>
/// <b>A capability, not a lookup.</b> The process that needs an identity holds no keys
/// and no vault connection, deliberately — it drives browsers against sites that have no
/// interest in being read, and a credential that could decrypt would be a standing right
/// sitting in the most exposed part of the system. So it asks a process that does hold
/// them, and what it presents is this: an unguessable secret minted for exactly one leg
/// of work. Presenting it is the authentication; this row only turns it into a name.
/// </para>
/// <para>
/// The alternative was to let the asker name the work — a scan id and a certificate — and
/// that is the shape this deliberately does not have. <b>A scan id is not a secret</b>: it
/// is generated by the service and handed straight back to whoever asked for the scan. A
/// grant resolvable from one would rest entirely on the transport being configured
/// correctly, which is a property of a deployment rather than of the schema. Keyed to a
/// digest, the release is as strong as the token whether or not the edge in front of it
/// is what anybody thinks it is.
/// </para>
/// <para>
/// <b>One leg of work, not one scan.</b> A scan fans out to a broker at a time, each paced
/// separately and each running whenever its lane allows, so one grant covering the whole
/// run would be a key with a long life and many holders. This is per broker, which keeps
/// what a leaked one opens down to a single company's leg.
/// </para>
/// <para>
/// The token itself is not here and never was: what is stored is its digest, so reading
/// this table yields nothing anybody can present.
/// </para>
/// </remarks>
public class IdentityRelease : ITenantScoped
{
    public Guid Id { get; init; }

    /// <summary>The account whose identity this permits reading.</summary>
    public Guid TenantId { get; init; }

    /// <summary>
    /// The run this leg belongs to, or <see langword="null"/> when this grant is for an
    /// attempt at a removal rather than a leg of a scan.
    /// </summary>
    /// <remarks>
    /// Exactly one of this and <see cref="RemovalJobId"/> is set, which the database checks.
    /// A grant naming neither would be a decryption right belonging to no work at all, and
    /// one naming both would be two pieces of work sharing a single-use token.
    /// </remarks>
    public Guid? ScanId { get; init; }

    /// <summary>
    /// The attempt this grant belongs to, or <see langword="null"/> when it is a scan leg's.
    /// </summary>
    /// <remarks>
    /// A connector filling in a company's form or composing a deletion demand needs a name
    /// exactly as a search does. Its own column rather than a shared one carrying a kind
    /// beside it, because a column that references nothing can name a row that does not
    /// exist — and the check that it does not would live in whichever code path remembered.
    /// </remarks>
    public Guid? RemovalJobId { get; init; }

    /// <summary>The company this leg is addressed to.</summary>
    public required Guid BrokerId { get; init; }

    /// <summary>Which identity is being released.</summary>
    /// <remarks>
    /// Read from the work at minting rather than accepted from the caller, so there is no
    /// second chance to name the wrong identity: the run already settled whose it searches
    /// for, and the demand already settled whose it is made on behalf of. The pairing the
    /// database enforces is with the <i>account</i> — a profile belonging to somebody else
    /// is refused — and not with the work, which is a weaker guarantee than this comment
    /// used to claim and is worth stating accurately.
    /// </remarks>
    public required Guid PrivacyProfileId { get; init; }

    /// <summary>
    /// SHA-256 of the token. The token is 256 bits from a CSPRNG, so there is nothing to
    /// guess and no reason to pay for a slow hash on a path a scan hits once per broker.
    /// </summary>
    public required byte[] TokenHash { get; init; }

    /// <summary>
    /// The groups this grant covers, and the ceiling on what redeeming it decrypts.
    /// </summary>
    /// <remarks>
    /// Recorded rather than recomputed at redemption. What a search declares it needs can
    /// change with a deploy; what was actually handed over on a Tuesday cannot, and the
    /// second is the question somebody asks afterwards.
    /// </remarks>
    public required IReadOnlyList<IdentityField> Fields { get; init; }

    public DateTimeOffset IssuedAt { get; init; }

    /// <summary>
    /// When it stops being redeemable, whether or not anybody used it.
    /// </summary>
    /// <remarks>
    /// Short, and short for a reason that is not about theft: a grant minted when a leg
    /// was queued and redeemed when its lane finally allowed it could otherwise sit
    /// unredeemed for as long as the queue is deep. A window that outlives the work is a
    /// window in which a message sitting in a queue is a decryption right.
    /// </remarks>
    public required DateTimeOffset ExpiresAt { get; init; }

    /// <summary>
    /// When it was spent, or <see langword="null"/> while it has not been.
    /// </summary>
    /// <remarks>
    /// A timestamp rather than a flag, because the question asked afterwards is when
    /// somebody's identity was decrypted and by which piece of work — and a boolean
    /// answers neither. This is the record the audit trail will carry when there is one;
    /// until then it is the record.
    /// </remarks>
    public DateTimeOffset? RedeemedAt { get; set; }

    /// <summary>
    /// When this leg recorded what it found, or <see langword="null"/> while it has not.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The grant's second single-use spend. A finding now carries the address of the listing
    /// it was found on, which is a copy of somebody's identity and belongs in the vault — so
    /// the process that finds listings can no more write one than it can read a name, and
    /// recording a finding became something it asks for with the grant it already holds.
    /// </para>
    /// <para>
    /// <b>Separate from <see cref="RedeemedAt"/> because they are separate permissions.</b>
    /// Opening an identity does not consume the right to say what was found with it, and the
    /// question asked afterwards — was an identity decrypted, were findings written — has two
    /// answers. A single column would give one.
    /// </para>
    /// </remarks>
    public DateTimeOffset? ReportedAt { get; set; }
}
