<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <UserSecretsId>dotnet-Dbr.Worker-9e492741-84e9-4a58-93b3-3b532cbfbeb0</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dbr.Infrastructure\Dbr.Infrastructure.csproj" />
  </ItemGroup>

</Project>
