-- SPDX-FileCopyrightText: 2026 Max Veregge
-- SPDX-License-Identifier: AGPL-3.0-or-later
--
-- Permission for one piece of work to see part of one identity, once.
--
-- The processes that talk to broker sites hold no key-manager credentials and no vault
-- connection string. That is deliberate and it is the whole reason this table exists: a
-- worker that needs somebody's name has to ask a process that holds the keys, and what it
-- presents when it asks is a row in here.
--
-- ---------------------------------------------------------------------------------
-- Why a token and not an id
-- ---------------------------------------------------------------------------------
--
-- The obvious design lets the asker name the work — "release the fields for scan X" —
-- and authenticates it by the transport, a client certificate on an internal listener.
-- Resolving that means reading a row before the caller is acting for any tenant, which
-- this schema does exactly twice, for passkeys and for refresh tokens. Both are safe for
-- a reason that does not carry over: their argument is an unguessable secret, so
-- presenting it *is* the authentication and the function only turns it into a name.
--
-- A scan id is not a secret. It is generated by the service and handed straight back to
-- the client that asked for the scan. A lookup keyed on one would be the weakest of the
-- three, and everything holding it up would be the certificate — a property of how a
-- deployment was configured rather than of this schema. So the grant is minted with 256
-- bits from a CSPRNG, and only the digest is kept. Keyed that way it is exactly as strong
-- as the token, whether or not the edge in front of it is what anybody thinks it is.
--
-- ---------------------------------------------------------------------------------
-- Why one row per broker
-- ---------------------------------------------------------------------------------
--
-- A scan fans out to one broker at a time, each leg paced separately and each running
-- whenever its lane allows. One grant covering the whole run would be a single key with a
-- long life and many holders; per broker, what a leaked one opens is one company's leg.

CREATE TABLE identity_release (
    id                 uuid        PRIMARY KEY DEFAULT gen_random_uuid(),

    tenant_id          uuid        NOT NULL REFERENCES tenant (id),

    scan_id            uuid        NOT NULL,

    -- Shared reference data, so no composite key to pair against — the same reasoning
    -- scan_broker records. RESTRICT by omission: a broker with grants against it is one
    -- somebody's history refers to.
    broker_id          uuid        NOT NULL REFERENCES broker (id),

    -- Denormalized from the scan and pinned to it below, so a grant cannot come to name a
    -- different profile than the run it was minted for.
    privacy_profile_id uuid        NOT NULL,

    -- The token is 256 bits from a CSPRNG, so there is nothing to guess and no reason to
    -- pay for a slow hash on a path a scan hits once per broker.
    token_hash         bytea       NOT NULL UNIQUE,

    -- What this grant covers, and the ceiling on what redeeming it decrypts.
    --
    -- Recorded rather than recomputed when it is spent. What a search declares it needs
    -- can change with a deploy; what was handed over on a Tuesday cannot, and the second
    -- is the question somebody asks afterwards.
    --
    -- Membership and non-emptiness are checked here. Distinctness is not, and cannot be:
    -- expressing "no duplicates" needs a subquery, which a CHECK constraint may not
    -- contain. The service builds this from a set, and a repeated element would decrypt
    -- the same group twice rather than widen anything — a tidiness failure, not a
    -- privilege one, which is why it is left to the caller.
    fields             text[]      NOT NULL
                                   CONSTRAINT identity_release_fields_known
                                   CHECK (
                                       cardinality(fields) > 0
                                       AND fields <@ ARRAY[
                                           'names',
                                           'addresses',
                                           'contacts',
                                           'date_of_birth']::text[]),

    issued_at          timestamptz NOT NULL DEFAULT now(),

    -- Short, and short for a reason that is not about theft. A grant minted when a leg was
    -- queued and redeemed when its lane finally allowed it could otherwise sit unredeemed
    -- for as long as the queue is deep, and a window that outlives the work is a window in
    -- which a message sitting in a queue is a decryption right.
    expires_at         timestamptz NOT NULL,

    -- When it was spent. A timestamp rather than a flag, because the question asked
    -- afterwards is when an identity was decrypted and for which piece of work, and a
    -- boolean answers neither.
    redeemed_at        timestamptz NULL,

    CONSTRAINT identity_release_scan_same_tenant
        FOREIGN KEY (tenant_id, scan_id)
        REFERENCES scan (tenant_id, id)
        ON DELETE CASCADE,

    CONSTRAINT identity_release_profile_same_tenant
        FOREIGN KEY (tenant_id, privacy_profile_id)
        REFERENCES privacy_profile (tenant_id, id),

    CONSTRAINT identity_release_expires_after_issue
        CHECK (expires_at > issued_at),

    CONSTRAINT identity_release_redeemed_after_issue
        CHECK (redeemed_at IS NULL OR redeemed_at >= issued_at)
);

COMMENT ON TABLE identity_release IS
    'Permission for one leg of one scan to see part of one identity, once. Presented as '
    'an unguessable token by a process that holds no keys; only the digest is stored, so '
    'reading this table yields nothing anybody can present.';

COMMENT ON COLUMN identity_release.fields IS
    'The groups this grant covers. Recorded at minting rather than recomputed at '
    'redemption, because what was actually handed over is the question asked afterwards.';

COMMENT ON COLUMN identity_release.expires_at IS
    'When it stops being redeemable, whether or not anybody used it. Sized to the work '
    'rather than to the queue: a window that outlives the leg makes a queued message a '
    'standing decryption right.';

-- Every grant for a run, which is how somebody answers "what was decrypted for this
-- scan" without the token that opened any of it.
CREATE INDEX identity_release_by_scan ON identity_release (tenant_id, scan_id);

CALL app.enable_tenant_rls('public.identity_release');

-- The application role may mint grants and read them, and may change exactly one thing
-- about one: that it has been spent. Everything else about a grant — which fields it
-- covers, when it expires, which work it belongs to, the digest that opens it — is
-- settled at minting and cannot be rewritten afterwards by the role that serves requests.
-- A widened scope or a pushed-out expiry would be the two most useful edits to an
-- attacker holding an application-level foothold, and neither is available.
--
-- DELETE is deliberately left in place, as it is on consent_record and for the same
-- reason: account deletion has to actually erase, and routing the one legitimate removal
-- path around the application role would make erasure the operation needing special
-- privileges.
REVOKE UPDATE ON identity_release FROM dbr_app;
GRANT UPDATE (redeemed_at) ON identity_release TO dbr_app;

-- ---------------------------------------------------------------------------------
-- Resolving a grant before the caller is acting for anybody
-- ---------------------------------------------------------------------------------
--
-- The third and last definer function in this schema, and the same narrow shape as the
-- other two: it answers only to a digest, and returns only what deciding the redemption
-- needs. A caller learning that a token they already hold is expired or spent learns
-- nothing they could not infer from being refused.
--
-- It returns no identifying data. The fields themselves live encrypted in the other
-- store, and getting at them needs the tenant this resolves to plus a key the key manager
-- has to unwrap — so this function on its own opens nothing.
CREATE FUNCTION app.find_identity_release(lookup_token_hash bytea)
    RETURNS TABLE (
        id uuid,
        tenant_id uuid,
        scan_id uuid,
        broker_id uuid,
        privacy_profile_id uuid,
        fields text[],
        expires_at timestamptz,
        redeemed_at timestamptz)
    LANGUAGE sql
    STABLE
    SECURITY DEFINER
    -- Everything below is schema-qualified and this path holds nothing else, so no object
    -- the body names can be shadowed by a caller-controlled schema.
    SET search_path = pg_catalog
AS $$
    SELECT release.id,
           release.tenant_id,
           release.scan_id,
           release.broker_id,
           release.privacy_profile_id,
           release.fields,
           release.expires_at,
           release.redeemed_at
    FROM public.identity_release AS release
    WHERE release.token_hash = lookup_token_hash
$$;

COMMENT ON FUNCTION app.find_identity_release(bytea) IS
    'Resolve a release token to the grant it opens, before the caller is acting for any '
    'tenant. Narrow by construction: it answers only to a token digest, returns no '
    'identifying data, and returns only the state deciding whether the grant may be '
    'spent.';

REVOKE ALL ON FUNCTION app.find_identity_release(bytea) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION app.find_identity_release(bytea) TO dbr_app;

-- As with the other two, there is no definer function that writes. Once the token
-- resolves the tenant is known, so spending the grant goes through the ordinary
-- policy-enforced path — under the column grant above, which is what keeps spending the
-- only thing that path can do to it.
